server:
  port: 8081
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8

dubbo:
  application:
    name: mall-manager-web
  registry:
    address: zookeeper://127.0.0.1:2181

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 1MB
      max-request-size: 10MB

# LOGGING
logging:
  level:
    root: info
#  pattern:
#    console: %5p %c{2} - &m&n


