server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/online_mall?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  servlet:
    multipart:
      enabled: true
      max-file-size: 1MB
      max-request-size: 10MB

  jpa:
    database: default
    # 开发时显示sql，部署到生产环境时设为false
    show-sql: true
    # 使用mysql方言
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      # 下面两个配置对应hibernate的属性
      ddl-auto: update
    properties:
      hibernate:
        # 格式化sql 语句
        format_sql: true

# LOGGING
logging:
  level:
    root: info