dubbo:
  application:
    name: mall-manager-web
  registry:
    address: zookeeper://47.106.183.240:2181
  consumer:
    timeout: 7000
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 1MB
      max-request-size: 10MB

#tomcat conf
server:
  port: 8081

# LOGGING
logging:
  level:
    root: info
#  pattern:
#    console: %5p %c{2} - &m&n


