#tomcat conf
server:
  port: 8077

spring:
  datasource:
    url: jdbc:mysql://boyce.top:3306/online_mall?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  data:
    solr:
      host: http://boyce.top:8983/solr/collection1

  activemq:
    user: admin
    password: admin
    broker-url: tcp://boyce.top:61616
    pool:
      enabled: true
      max-connections: 50
    packages:
      trust-all: false

dubbo:
  application:
    name: mall-search
  registry:
    address: zookeeper://boyce.top:2181
  scan:
    basePackages: cn.boyce.search.service.impl
  protocol:
    port: 20882