dubbo:
  application:
    name:
      mall-manager
  registry:
    address: zookeeper://127.0.0.1:2181
  scan:
    basePackages: cn.boyce.manager.service.impl
    #    base-packages: cn.boyce.manager.service.impl
    #（由于官方 bug 扫描包配置是 basePackages，而非 base-packages）

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/online_mall?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: default
    # 开发时显示sql，部署到生产环境时设为false
    show-sql: true
    # 使用mysql方言
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      # 下面两个配置对应hibernate的属性
      ddl-auto: update
    properties:
      hibernate:
      # 格式化sql 语句
      format_sql: true
    open-in-view: false


# LOGGING 以下配置上会无法启动
#logging:
#  level:
#    root: info
#  pattern:
#    console: %5p %c{2} - &m&n