dubbo:
  application:
    name: mall-content
  registry:
    address: zookeeper://47.106.183.240:2181
  scan:
    basePackages: cn.boyce.content.service.impl
  protocol:
    port: 20881

#tomcat conf
server:
  port: 8078

spring:
  datasource:
    url: jdbc:mysql://47.106.183.240:3306/online_mall?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: default
    # 开发时显示sql，部署到生产环境时设为false
    show-sql: true
    # 使用mysql方言
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      # 下面两个配置对应hibernate的属性
      ddl-auto: update
    properties:
      hibernate:
      # 格式化sql 语句
      format_sql: true
    open-in-view: false
  # Redis 配置
  redis:
    timeout: 5000
    host: 47.106.183.240
    port: 6379
